
package sistemasjym.ui;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import sistemasjym.controlador.ControladorProveedor;
import sistemasjym.servicios.ConectarServicio;
import sistemasjym.servicios.Conexion;

public class Frm_Proveedores extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Proveedores
     */
    public Frm_Proveedores() {
        initComponents();
        cargarProveedores();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        razon_social = new org.edisoncor.gui.textField.TextField();
        ruc = new org.edisoncor.gui.textField.TextField();
        direccion = new org.edisoncor.gui.textField.TextField();
        telefono = new org.edisoncor.gui.textField.TextField();
        panelNice2 = new org.edisoncor.gui.panel.PanelNice();
        registrar = new org.edisoncor.gui.button.ButtonTask();
        MODIFICAR = new org.edisoncor.gui.button.ButtonTask();
        ELIMINAR = new org.edisoncor.gui.button.ButtonTask();
        LIMPIAR = new org.edisoncor.gui.button.ButtonTask();
        panelNice3 = new org.edisoncor.gui.panel.PanelNice();
        jLabel2 = new javax.swing.JLabel();
        panelNice4 = new org.edisoncor.gui.panel.PanelNice();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProveedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNice1.setBackground(new java.awt.Color(0, 0, 0));
        panelNice1.setAnchoDeBorde(3.0F);
        panelNice1.setBorderColor(new java.awt.Color(255, 255, 0));
        panelNice1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RAZON SOCIAL :");
        panelNice1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DIRECCION :");
        panelNice1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TELEFONO :");
        panelNice1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("RUC :");
        panelNice1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        razon_social.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelNice1.add(razon_social, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 250, -1));

        ruc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelNice1.add(ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 250, -1));

        direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelNice1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 250, -1));

        telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelNice1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 250, -1));

        jPanel1.add(panelNice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 420, 200));

        panelNice2.setBackground(new java.awt.Color(0, 0, 0));
        panelNice2.setAnchoDeBorde(3.0F);
        panelNice2.setBorderColor(new java.awt.Color(255, 255, 0));
        panelNice2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrar.setForeground(new java.awt.Color(255, 255, 0));
        registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasjym/utilitarios/guardar.png"))); // NOI18N
        registrar.setText("REGISTRAR");
        registrar.setDescription(" ");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        panelNice2.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        MODIFICAR.setForeground(new java.awt.Color(255, 255, 0));
        MODIFICAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasjym/utilitarios/actualizar.png"))); // NOI18N
        MODIFICAR.setText("MODIFICAR");
        MODIFICAR.setDescription(" ");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });
        panelNice2.add(MODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 190, -1));

        ELIMINAR.setForeground(new java.awt.Color(255, 255, 0));
        ELIMINAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasjym/utilitarios/eliminar.png"))); // NOI18N
        ELIMINAR.setText("ELIMINAR");
        ELIMINAR.setDescription(" ");
        ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELIMINARActionPerformed(evt);
            }
        });
        panelNice2.add(ELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 190, -1));

        LIMPIAR.setForeground(new java.awt.Color(255, 255, 0));
        LIMPIAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasjym/utilitarios/limpiar.png"))); // NOI18N
        LIMPIAR.setText("LIMPIAR");
        LIMPIAR.setDescription(" ");
        panelNice2.add(LIMPIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 190, -1));

        jPanel1.add(panelNice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 610, 140));

        panelNice3.setBackground(new java.awt.Color(0, 0, 0));
        panelNice3.setAnchoDeBorde(3.0F);
        panelNice3.setBorderColor(new java.awt.Color(255, 255, 0));
        panelNice3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("REGISTRO DE PROVEEDORES");
        panelNice3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, -1, -1));

        jPanel1.add(panelNice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 350, 90));

        panelNice4.setBackground(new java.awt.Color(0, 0, 0));
        panelNice4.setAnchoDeBorde(3.0F);
        panelNice4.setBorderColor(new java.awt.Color(255, 0, 0));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("AQUI USTED PODRA REGISTRAR, ACTUALIZAR, ELIMINAR  LOS REGISTROS DE CADA UNO DE SUS PROVEEDORES ");

        javax.swing.GroupLayout panelNice4Layout = new javax.swing.GroupLayout(panelNice4);
        panelNice4.setLayout(panelNice4Layout);
        panelNice4Layout.setHorizontalGroup(
            panelNice4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelNice4Layout.setVerticalGroup(
            panelNice4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelNice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1080, 40));

        tblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblProveedoresMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblProveedores);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 227, 650, 240));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        try {
            String rc=ruc.getText();
            String rz=razon_social.getText();
            String dir=direccion.getText();
            String tel=telefono.getText();       
            
            ControladorProveedor cp = new ControladorProveedor();        
            cp.agregarProveedor(rc,rz,dir,tel);
            LimpiarCajasTexto();
            cargarProveedores();          
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException ex) {
            JOptionPane.showMessageDialog(null,"El ruc" + ruc.getText() + " ya existe, ingrese un ruc distinto","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
        try {
            String rc=ruc.getText();
            String rz=razon_social.getText();
            String dir=direccion.getText();
            String tel=telefono.getText();       
            
            ControladorProveedor cp = new ControladorProveedor();        
            cp.modificarProveedor(rc,rz,dir,tel);
            LimpiarCajasTexto();
            cargarProveedores();          
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException ex) {
            JOptionPane.showMessageDialog(null,"El ruc" + ruc.getText() + " ya existe, ingrese un ruc distinto","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void tblProveedoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProveedoresMousePressed
        int clie = this.tblProveedores.getSelectedRow();
        ruc.setEditable(false);
        registrar.setEnabled(false);
        ELIMINAR.setEnabled(true);
        try {          
            this.ruc.setText(tblProveedores.getValueAt(clie, 1).toString());
            this.razon_social.setText(tblProveedores.getValueAt(clie, 2).toString());
            this.direccion.setText(tblProveedores.getValueAt(clie, 3).toString());
            this.telefono.setText(tblProveedores.getValueAt(clie, 4).toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar datos de el proveedor", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblProveedoresMousePressed

    private void ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELIMINARActionPerformed
       try {
            String rc=ruc.getText();     
          
            ControladorProveedor cp = new ControladorProveedor();        
            cp.eliminarProveedor(rc);
            LimpiarCajasTexto();
            cargarProveedores();          
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            JOptionPane.showMessageDialog(null,"Error en la eliminacion del registro","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ELIMINARActionPerformed

    //Metodo para cargar la tabla proveedores
    
    public void cargarProveedores(){
        DefaultTableModel m;
        try {
            String titulo[]={"Nro","Ruc","Razon Social","Direccion","Telefono"};
            m= new DefaultTableModel(null, titulo);
            JTable p = new JTable(m);
            String fila[]= new String[6];
            Conexion cdb= ConectarServicio.getInstancia().getConexionDb();            
            cdb.un_sql="select * from proveedor";
            cdb.resultado= cdb.us_st.executeQuery(cdb.un_sql);
            int index =1;
            
            while(cdb.resultado.next()){
                fila[0]=String.valueOf(index);
                fila[1]= cdb.resultado.getString(1);
                fila[2]= cdb.resultado.getString(2);
                fila[3]= cdb.resultado.getString(3);
                fila[4]= cdb.resultado.getString(4);
                m.addRow(fila);
                index++;
            }
            tblProveedores.setModel(m);
            TableRowSorter<TableModel> ordenar = new TableRowSorter<TableModel>(m);
            tblProveedores.setRowSorter(ordenar);
            this.tblProveedores.setModel(m);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error al extraer los datos de la tabla","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /*Meotod para limpiar las cajas de texto */
    public void LimpiarCajasTexto(){
        ruc.setText("");
        razon_social.setText("");
        direccion.setText("");
        telefono.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Proveedores().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTask ELIMINAR;
    private org.edisoncor.gui.button.ButtonTask LIMPIAR;
    private org.edisoncor.gui.button.ButtonTask MODIFICAR;
    private org.edisoncor.gui.textField.TextField direccion;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    private org.edisoncor.gui.panel.PanelNice panelNice2;
    private org.edisoncor.gui.panel.PanelNice panelNice3;
    private org.edisoncor.gui.panel.PanelNice panelNice4;
    private org.edisoncor.gui.textField.TextField razon_social;
    private org.edisoncor.gui.button.ButtonTask registrar;
    private org.edisoncor.gui.textField.TextField ruc;
    private javax.swing.JTable tblProveedores;
    private org.edisoncor.gui.textField.TextField telefono;
    // End of variables declaration//GEN-END:variables
}
